name: Build CI

on:
  - workflow_dispatch
  - push

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build_native_linux:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    runs-on: ubuntu-latest
    container: mono:6.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 2.1.607
      - run: |
          apt-get update && apt-get install -y g++-multilib g++ make
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/build.cake
          target: BuildNativeLinux
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/samples.cake
          target: BuildNativeLinuxLibs
      - uses: actions/upload-artifact@v2
        with:
          name: build_linux
          path: |
            native/bin
            native-lib/bin
  build_native_windows:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v2
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/build.cake
          target: BuildNativeWindows
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/samples.cake
          target: BuildNativeWindowsLibs
      - uses: actions/upload-artifact@v2
        with:
          name: build_windows
          path: |
            native/bin
            native-lib/bin
  compress_native:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: [build_native_linux, build_native_windows]
    runs-on: ubuntu-latest
    container: mono:6.6
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: build_linux
      - uses: actions/download-artifact@v2
        with:
          name: build_windows
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 2.1.607
      - run: |
          apt-get update && apt-get install -y make zstd
          cd csharp
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/build.cake
          target: CompressNative
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/samples.cake
          target: CompressNativeLibs
      - uses: actions/upload-artifact@v2
        with:
          name: compressed
          path: |
            native/bin
            native-lib/bin
  test_java8_linux:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: compress_native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/download-artifact@v2
        with:
          name: compressed
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: check
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: run
      - uses: actions/upload-artifact@v2
        with:
          name: test_java_linux
          path: |
            java/main/build/reports/tests
  test_java8_windows:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: compress_native
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/download-artifact@v2
        with:
          name: compressed
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: check
      - uses: eskatos/gradle-command-action@v1.3.3
        with:
          arguments: run
      - uses: actions/upload-artifact@v2
        with:
          name: test_java_windows
          path: |
            java/main/build/reports/tests
  test_dotnet_linux:
    if: |
      ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: compress_native
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/download-artifact@v2
        with:
          name: compressed
      - uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 2.1.607
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/build.cake
          target: Run-Unit-Tests
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            csharp/Functions.Dll/bin
  test_dotnet_windows:
    if: |
      ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}
    needs: compress_native
    runs-on: [self-hosted, Windows]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/download-artifact@v2
        with:
          name: compressed
      - uses: cake-build/cake-action@v1.2.0
        with:
          script-path: csharp/build.cake
          target: Run-Unit-Tests
      - uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            csharp/Functions.Dll/bin
